### ISSUE TITLE
ERROR: Incompatible dimensions (GE analysis)

### ISSUE THREAD

**Issue by pageale** [kircherlab/cfDNA#12]
Hello, i was trying to run the GE analysis pipeline but i experimented an Error in rule correlation_plots, since the matrices have different dimensions and either they have similar row names, so I am not sure if this is an issue with the file generated in the previous step (transcriptanno-{SAMPLE}-FFT_table.{GENOME}.tsv")

`
[1] 19617    24
[1] 19285    19
`

Also, I would like to know what these lines means or what they are referring to (if i have to change it or not).

* fftColumns <- 29:52 # 160-222
* selFreq <- c("193","196","199")

Related to the config.yml, I kept the same parameters as the example (for the cells and 'blood' for the atlas)

```
##################################

tLabels <- read.table(snakemake@input[["labels"]],header=T,as.is=T,sep="\t",quote="\"")

fftColumns <- 29:52 # 160-222
selFreq <- c("193","196","199")

library(gplots)

##################################
open the pdf
  pdf(snakemake@output[["allFreq"]],width=8,height=6)

  for (sample in samples)
  {
    fdata <- read.table(sample,as.is=T,sep="\t",header=T,comment.char="~")
    colnames(fdata) <- sub("X","",colnames(fdata))
    #rownames(fdata) <- fdata[,1]
    print('pass')
    ## reorder, only the first stays and the rest in reverse order
    fdata <- fdata[,c(1,rev(c(2:dim(fdata)[2])))]
    logndata2 <- logndata[fdata[,1],]
    # Extracts the sample name from the file path by splitting and extracting 
    # the relevant part of the filename
    sample_name <- strsplit(tail(strsplit(sample, "/")[[1]],1),"-")[[1]][2]
    print('pass2')
    print(dim(fdata[, fftColumns]))
    print(dim(logndata2))
    
    ## calculates the correlation 
    res <- cor(fdata[,fftColumns, NA],logndata2,use="pairwise.complete.obs")

    matplot(as.numeric(sub("X","",names(fdata[,fftColumns]))),res,type="l",xlab="Frequency",ylab="Correlation",col="darkgrey",lwd=1,lty=1,main=sprintf("%s: Correlation of intensities across tissues",sample_name))
    lines(as.numeric(sub("X","",names(fdata[,fftColumns]))),cor(fdata[,fftColumns],logndata2[,tissue],method="pearson",use="pairwise.complete.obs"),col="black",lwd=2,type="b",pch=19,cex=0.6)
    legend("topright",tissue,fill="black")
  }
  dev.off()
```

I would appreciate your response !!

thx

**Comment by sroener** [comment]
Hi @pageale,

> Hello, i was trying to run the GE analysis pipeline but i experimented an Error in rule correlation_plots, since the matrices have different dimensions and either they have similar row names, so I am not sure if this is an issue with the file generated in the previous step (transcriptanno-{SAMPLE}-FFT_table.{GENOME}.tsv")
>
>[1] 19617    24 [1] 19285    19

This might be an issue with the file. There are some changes in the develop branch, that might with that specific error. Could you please try, and report back whether that fixed your specific error.

>Also, I would like to know what these lines means or what they are referring to (if i have to change it or not).
>
>    fftColumns <- 29:52 # 160-222
>   selFreq <- c("193","196","199")

These parameters are hard coded, as they were used in the Gene Expression analysis of Snyder et al. The script produces Figure 5 E of the paper. The first parameter (fftColumns) specifies the inferred nucleosome distance (160-222 bp) based on the FFT period lengths. The second parameter (selFreq) is a parameter that is not used in this plot. It is the empirical determined range of Nucleosome spacings with the highest (negative) correlation with expression. These values are used in the downstream expression analysis shown in Figure 5 F. 

I hope I could answer your questions.

**Comment by pageale** [comment]
Thank you so much !! I already figure out which was the issue with the input file and everything is running smoothly !

**Comment by pageale** [comment]
Also, I am not sure if this is the correct mean to ask this but I will open other issue for output interpretation.

**Comment by sroener** [comment]
Good to here that you could fix the error. I will close the issue.
If there any further questions regarding this issue, feel free to reopen.
