### ISSUE TITLE
WPS & overlays 

### ISSUE THREAD

**Issue by madil7173** [kircherlab/cfDNA#5]
Hi, 
I recently started using the workflows again and I finally got the WPS workflow to work and I noticed that the output has unexpected results near the right end. I am not sure why it is doing that, and why its not doing the same on the left side. 
Any thoughts? 

[placenta.PDNAS_251PE02_HighFF30_overlays.pdf](https://github.com/kircherlab/cfDNA/files/5548093/placenta.PDNAS_251PE02_HighFF30_overlays.pdf)

**Comment by sroener** [comment]
Hi,

could you please provide me with some example input data? I might have an idea what happened, but I would like to be sure.

**Comment by madil7173** [comment]
Ya, so I tried both bed file with 1. Start and stop one bp apart and 2. Start and stop being the same. In both cases that tailing was still present.

**Comment by madil7173** [comment]
chr	str	Stop	cell	val	strand
1	540651	540651	Placenta	0	+
1	672842	672842	Placenta	0	+
1	706337	706337	Placenta	0	+
1	785933	785933	Placenta	0	+
1	812383	812383	Placenta	0	+

**Comment by madil7173** [comment]
Thanks for looking into it. I have sampled the first few lines of my input bed file above.

**Comment by sroener** [comment]
Hi, I run some analyses and everything seems to work correctly. 

I assume that your .bam files has no reads around the end of the flaking regions, which leads to this weird artefacts in the plots.

Could you please check, whether the WPS/Coverage values in the intermediate tables (/results/intermediate/table/...) are 0 in the last columns.

**Comment by sroener** [comment]
Hi,

I made some changes to the WPS workflow on the develop branch (added more padding to the regions). Could you try, whether this fixes the plotting artefacts or not?

**Comment by madil7173** [comment]
Hi,
The env is missing the background.yml file which is newly added on the updated snakefile_WPS.smk.
Best,
Adil

**Comment by sroener** [comment]
Hi,
you are absolutely right. I fixed it. Please pull the develop branch again and try to run the workflow.

**Comment by madil7173** [comment]
Perfect its running now. For some reason I always have issues with importing pysam 0.7.6 I am not sure why but pysam 0.7.7 installs fine so I just changed the dependency to 0.7.7 in the yml file and it runs to completion. Do you think that might have an impact on the pipeline?

**Comment by sroener** [comment]
Good to hear that everything is running now. 

Changing the dependency from 0.7.6 to 0.7.7 should not be a problem. If there are errors related to pysam, please open a new issue describing the problem ;-)

I close the issue now as solved. If there are any further problems/plotting artifacts, feel free to reopen.

**Comment by madil7173** [comment]
Hi, 
The script failed for me for some reason, it did generate the intermediate WPS COV tables. I have pasted the error below.  

Activating conda environment: /mnt/disk3/research/madil/kirchirlab/develop_cfDNA/cfDNA/.snakemake/conda/2e6d913f
Using min/max length cutoffs: 120/180
Traceback (most recent call last):
  File "workflow/scripts/WPS/extractFromBAM_RegionBed_WPS_Cov.py", line 107, in <module>
    for read in input_file.fetch(chrom,regionStart-protection-1,regionEnd+protection+1):
  File "csamtools.pyx", line 1059, in pysam.csamtools.Samfile.fetch (pysam/csamtools.c:12490)
  File "csamtools.pyx", line 990, in pysam.csamtools.Samfile._parseRegion (pysam/csamtools.c:11697)
ValueError: invalid reference `chr2`

**RuleException:
CalledProcessError in line 156 of /mnt/disk3/research/madil/kirchirlab/develop_cfDNA/cfDNA/snakefile_WPS.smk:**
Command 'source activate /mnt/disk3/research/madil/kirchirlab/develop_cfDNA/cfDNA/.snakemake/conda/2e6d913f; set -euo pipefail;

File "/mnt/disk3/research/madil/kirchirlab/develop_cfDNA/cfDNA/snakefile_WPS.smk", line 156, in rule_extract_counts_background
File "/home/local/AMC/madil/miniconda3/envs/bio/lib/python3.6/concurrent/futures/thread.py", line 56, in run
